
- name: Intall Java application
  hosts: all
  become: true

  vars:
    source_dir: "files"
    dest_dir: /home/ubuntu/
    files:
      - app_properties.py
      - start.sh
      - spring-petclinic-3.1.0-SNAPSHOT.jar
  roles:
    - Java